import 'package:deliverzler/core/core_features/theme/presentation/utils/colors/custom_colors.dart';
import 'package:flutter/material.dart';
import 'package:deliverzler/core/presentation/styles/font_styles.dart';
import 'package:deliverzler/core/presentation/styles/sizes.dart';

class CustomText extends Container {
  CustomText._(
    BuildContext context,
    String text, {
    Key? key,
    double? size,
    color,
    weight,
    width,
    bool underline = false,
    strutStyle,
    textAlign,
    textDirection,
    locale,
    softWrap,
    overflow,
    textScaleFactor,
    maxLines,
    semanticsLabel,
    textWidthBasis,
    height,
    textHeightBehavior,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    Alignment? alignment,
  }) : super(
            key: key,
            margin: margin,
            padding: padding,
            alignment: alignment ?? AlignmentDirectional.topStart,
            width: width,
            child: Text(
              text,
              style: TextStyle(
                color: color,
                height: height,
                fontSize: size,
                fontWeight: weight,
                decoration: underline ? TextDecoration.underline : null,
                fontFamily: FontStyles.fontFamily(context),
              ),
              strutStyle: strutStyle,
              textAlign: textAlign,
              textDirection: textDirection,
              locale: locale,
              softWrap: softWrap,
              overflow: overflow,
              textScaleFactor: textScaleFactor,
              maxLines: maxLines,
              semanticsLabel: semanticsLabel,
              textWidthBasis: textWidthBasis,
              textHeightBehavior: textHeightBehavior,
            ));

  CustomText.f32(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    bool? underline,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          maxLines: maxLines,
          size: Sizes.font32(context),
          padding: padding,
          margin: margin,
          height: height,
          color: color ?? customColors(context).font32Color,
          weight: weight ?? FontStyles.fontWeightBlack,
          textAlign: textAlign,
          alignment: alignment,
        );

  CustomText.f24(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    int? maxLines,
    dynamic overflow,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          padding: padding,
          margin: margin,
          size: Sizes.font24(context),
          color: color ?? customColors(context).font24Color,
          weight: weight ?? FontStyles.fontWeightBlack,
          textAlign: textAlign,
          height: height,
          maxLines: maxLines,
          overflow: overflow,
          alignment: alignment,
        );

  CustomText.f20(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    bool underline = false,
    dynamic overflow,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          maxLines: maxLines,
          size: Sizes.font20(context),
          padding: padding,
          margin: margin,
          height: height,
          color: color ?? customColors(context).font20Color,
          weight: weight,
          textAlign: textAlign,
          underline: underline,
          overflow: overflow,
          alignment: alignment,
        );

  CustomText.f18(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    bool underline = false,
    dynamic overflow,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          padding: padding,
          margin: margin,
          size: Sizes.font18(context),
          color: color ?? customColors(context).font17Color,
          weight: weight,
          height: height,
          textAlign: textAlign,
          underline: underline,
          maxLines: maxLines,
          overflow: overflow,
          alignment: alignment,
        );

  CustomText.f16(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    bool underline = false,
    dynamic overflow,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          padding: padding,
          margin: margin,
          size: Sizes.font16(context),
          color: color ?? customColors(context).font17Color,
          weight: weight,
          height: height,
          textAlign: textAlign,
          underline: underline,
          maxLines: maxLines,
          overflow: overflow,
          alignment: alignment,
        );

  CustomText.f14(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    dynamic overflow,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          maxLines: maxLines,
          size: Sizes.font14(context),
          padding: padding,
          margin: margin,
          height: height,
          color: color ?? customColors(context).font14Color,
          weight: weight,
          overflow: overflow,
          textAlign: textAlign,
          alignment: alignment,
        );

  CustomText.f12(
    BuildContext context,
    String text, {
    Key? key,
    Color? color,
    FontWeight? weight,
    TextAlign? textAlign,
    dynamic overflow,
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    double? height,
    int? maxLines,
    Alignment? alignment,
  }) : this._(
          context,
          text,
          key: key,
          maxLines: maxLines,
          size: Sizes.font12(context),
          padding: padding,
          margin: margin,
          height: height,
          overflow: overflow,
          color: color ?? customColors(context).font12Color,
          weight: weight,
          textAlign: textAlign,
          alignment: alignment,
        );
}
