// Mocks generated by Mockito 5.3.2 from annotations
// in deliverzler/test/core/core_features/theme/presentation/providers/app_theme_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:deliverzler/core/core_features/theme/domain/repos/i_theme_repo.dart'
    as _i2;
import 'package:deliverzler/core/core_features/theme/domain/use_cases/get_app_theme_uc.dart'
    as _i3;
import 'package:deliverzler/core/core_features/theme/domain/use_cases/set_app_theme_uc.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIThemeRepo_0 extends _i1.SmartFake implements _i2.IThemeRepo {
  _FakeIThemeRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAppThemeUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppThemeUC extends _i1.Mock implements _i3.GetAppThemeUC {
  MockGetAppThemeUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IThemeRepo get themeRepo => (super.noSuchMethod(
        Invocation.getter(#themeRepo),
        returnValue: _FakeIThemeRepo_0(
          this,
          Invocation.getter(#themeRepo),
        ),
      ) as _i2.IThemeRepo);
  @override
  _i4.Future<String> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}

/// A class which mocks [SetAppThemeUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetAppThemeUC extends _i1.Mock implements _i5.SetAppThemeUC {
  MockSetAppThemeUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IThemeRepo get themeRepo => (super.noSuchMethod(
        Invocation.getter(#themeRepo),
        returnValue: _FakeIThemeRepo_0(
          this,
          Invocation.getter(#themeRepo),
        ),
      ) as _i2.IThemeRepo);
  @override
  _i4.Future<void> call(String? themeString) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [themeString],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
