include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # Enable riverpod_lint
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  # Disabling invalid_annotation_target warning.
  # If you plan on using Freezed in combination with json_serializable, recent versions of json_serializable and meta may require you to disable the invalid_annotation_target warning.
  errors:
    invalid_annotation_target: ignore

custom_lint:
  rules:

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false # Incompatible with: prefer_relative_imports.
    cascade_invocations: false
    directives_ordering: false # Conflicts with import_sorter
    avoid_multiple_declarations_per_line: false
