// Mocks generated by Mockito 5.3.2 from annotations
// in deliverzler/test/core/presentation/extensions/responsive_extension_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:deliverzler/core/presentation/services/responsive_service.dart'
    as _i6;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter/rendering.dart' as _i4;
import 'package:flutter/src/widgets/notification_listener.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeEdgeInsets_3 extends _i1.SmartFake implements _i4.EdgeInsets {
  _FakeEdgeInsets_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  MockBuildContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);
  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
      ) as bool);
  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);
  @override
  void visitAncestorElements(bool Function(_i2.Element)? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispatchNotification(_i5.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);
  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);
  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);
  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}

/// A class which mocks [ResponsiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponsiveService extends _i1.Mock implements _i6.ResponsiveService {
  MockResponsiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get minHeightMode => (super.noSuchMethod(
        Invocation.getter(#minHeightMode),
        returnValue: false,
      ) as bool);
  @override
  double get minHeight => (super.noSuchMethod(
        Invocation.getter(#minHeight),
        returnValue: 0.0,
      ) as double);
  @override
  double get deviceTopPadding => (super.noSuchMethod(
        Invocation.getter(#deviceTopPadding),
        returnValue: 0.0,
      ) as double);
  @override
  double get deviceBottomPadding => (super.noSuchMethod(
        Invocation.getter(#deviceBottomPadding),
        returnValue: 0.0,
      ) as double);
  @override
  double get deviceBottomViewPadding => (super.noSuchMethod(
        Invocation.getter(#deviceBottomViewPadding),
        returnValue: 0.0,
      ) as double);
  @override
  _i4.EdgeInsets get paddingFromFlutterWindow => (super.noSuchMethod(
        Invocation.getter(#paddingFromFlutterWindow),
        returnValue: _FakeEdgeInsets_3(
          this,
          Invocation.getter(#paddingFromFlutterWindow),
        ),
      ) as _i4.EdgeInsets);
  @override
  _i4.EdgeInsets get viewPaddingFromFlutterWindow => (super.noSuchMethod(
        Invocation.getter(#viewPaddingFromFlutterWindow),
        returnValue: _FakeEdgeInsets_3(
          this,
          Invocation.getter(#viewPaddingFromFlutterWindow),
        ),
      ) as _i4.EdgeInsets);
  @override
  double fullScreenHeight(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #fullScreenHeight,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double fullScreenWidth(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #fullScreenWidth,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double availableScreenHeight(_i2.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #availableScreenHeight,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double availableScreenWidth(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #availableScreenWidth,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double deviceKeyboardHeight(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #deviceKeyboardHeight,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double textScaleFactor(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #textScaleFactor,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double devicePixelRatio(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #devicePixelRatio,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  _i2.Orientation orientation(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #orientation,
          [context],
        ),
        returnValue: _i2.Orientation.portrait,
      ) as _i2.Orientation);
  @override
  double scaleWidth(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #scaleWidth,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double scaleHeight(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #scaleHeight,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double scaleRadius(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #scaleRadius,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  double scaleText(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #scaleText,
          [context],
        ),
        returnValue: 0.0,
      ) as double);
}
