// Mocks generated by Mockito 5.3.2 from annotations
// in deliverzler/test/core/core_features/locale/presentation/providers/app_locale_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:deliverzler/core/core_features/locale/domain/repos/i_locale_repo.dart'
    as _i2;
import 'package:deliverzler/core/core_features/locale/domain/use_cases/get_app_locale_uc.dart'
    as _i3;
import 'package:deliverzler/core/core_features/locale/domain/use_cases/set_app_locale_uc.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeILocaleRepo_0 extends _i1.SmartFake implements _i2.ILocaleRepo {
  _FakeILocaleRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAppLocaleUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppLocaleUC extends _i1.Mock implements _i3.GetAppLocaleUC {
  MockGetAppLocaleUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILocaleRepo get localeRepo => (super.noSuchMethod(
        Invocation.getter(#localeRepo),
        returnValue: _FakeILocaleRepo_0(
          this,
          Invocation.getter(#localeRepo),
        ),
      ) as _i2.ILocaleRepo);
  @override
  _i4.Future<String> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}

/// A class which mocks [SetAppLocaleUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetAppLocaleUC extends _i1.Mock implements _i5.SetAppLocaleUC {
  MockSetAppLocaleUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILocaleRepo get localeRepo => (super.noSuchMethod(
        Invocation.getter(#localeRepo),
        returnValue: _FakeILocaleRepo_0(
          this,
          Invocation.getter(#localeRepo),
        ),
      ) as _i2.ILocaleRepo);
  @override
  _i4.Future<void> call(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [languageCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
