Map<String, String> ordersAr = {
  'thereAreNoOrders': 'لا يوجد طلبات في الوقت الحالي.',
  'orderUpcoming': 'الطلب جاهز',
  'orderOnTheWay': 'الطلب في الطريق',
  'details': 'التفاصيل',
  'deliver': 'قم بالتوصيل',
  'showMap': 'أظهر الخريطة',
  'orderDetails': 'تفاصيل الطلب',
  'id': 'الرمز',
  'status': 'النوع',
  'payment': 'الدفع',
  'userDetails': 'بيانات المستخدم',
  'note': 'ملاحظة',
  'none': 'لا يوجد',
  'reasonForCancelingTheOrder': 'سبب إلغاء الطلب',
  'typeYourNote': 'اكتب ملاحظتك',
  'areYouSure': 'هل أنت متأكد',
  'doYouWantToDeliverTheOrder': 'هل تريد توصيل هذا الطلب؟',
  'doYouWantToConfirmTheOrder': 'هل تريد تأكيد توصيل هذا الطلب؟',
  'youCanNotProceedThisOrder': 'لا يمكنك تنفيذ هذا الطلب!',
  'youCanOnlyProceedOrdersYouDelivering':
      'يمكنك تنفيذ الطلبات التي تقوم بتوصيلها فقط.',
  'arrivedLocation': 'تم الوصول للموقع!',
  'youAreCloseToLocationArea': 'أنت قريب من الموقع. تم تفعيل تأكيد الطلب.',
};
