Map<String, String> ordersEn = {
  'thereAreNoOrders': 'There\'re no orders to be delivered.',
  'orderUpcoming': 'Order Upcoming',
  'orderOnTheWay': 'Order OnTheWay',
  'details': 'Details',
  'deliver': 'Deliver',
  'showMap': 'Show Map',
  'orderDetails': 'Order Details',
  'id': 'Id',
  'status': 'Status',
  'payment': 'Payment',
  'userDetails': 'User Details',
  'note': 'Note',
  'none': 'None',
  'reasonForCancelingTheOrder': 'Reason for canceling the order',
  'typeYourNote': 'Type your note',
  'areYouSure': 'Are you sure?',
  'doYouWantToDeliverTheOrder': 'Do you want to Deliver the order?',
  'doYouWantToConfirmTheOrder': 'Do you want to Confirm the order?',
  'youCanNotProceedThisOrder': 'You can\'t proceed this order!',
  'youCanOnlyProceedOrdersYouDelivering':
      'You can only proceed orders that you\'re delivering.',
  'arrivedLocation': 'Arrived Location!',
  'youAreCloseToLocationArea':
      'You\'re close to location area. Order delivery confirmation has enabled.',
};
