// Mocks generated by Mockito 5.3.2 from annotations
// in deliverzler/test/auth/presentation/providers/sign_out_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:deliverzler/auth/domain/repos/i_auth_repo.dart' as _i2;
import 'package:deliverzler/auth/domain/use_cases/sign_out_uc.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIAuthRepo_0 extends _i1.SmartFake implements _i2.IAuthRepo {
  _FakeIAuthRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignOutUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUC extends _i1.Mock implements _i3.SignOutUC {
  MockSignOutUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IAuthRepo get authRepo => (super.noSuchMethod(
        Invocation.getter(#authRepo),
        returnValue: _FakeIAuthRepo_0(
          this,
          Invocation.getter(#authRepo),
        ),
      ) as _i2.IAuthRepo);
  @override
  _i4.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
