Map<String, String> coreAr = {
  'appName': 'Deliverzler',
  'fontFamily': 'tajawal',
  'dateFormat': 'ar',
  'noInternetConnection': 'لا يوجد اتصال بالانترنت',
  'pleaseCheckYourDeviceNetwork': 'الرجاء إصلاح اتصالك بالانترنت.',
  'retry': 'إعادة المحاولة',
  'oops': 'عذراً!',
  'somethingWentWrong': 'لقد حدث خطاً.',
  'pleaseTryAgainLater': 'حاول مرة أخرى لاحقاً!',
  "ThisFieldIsEmpty": "هذا الحقل فارغ",
  "pleaseEnterValidNumber": "الرجاء ادخال رقم هاتف صحيح",
  "pleaseEnterValidEmail": "الرجاء ادخال بريد الكتروني صحيح",
  "pleaseEnterValidName": "الرجاء ادخال اسم صحيح",
  "nameMustBeAtLeast2Letters": "الاسم لا يمكن أن يكون أقل من حرفين",
  "nameMustBeAtMost30Letters": "الاسم لا يمكن أن يتخطى ٣٠ حرف",
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'back': 'الرجوع',
  'edit': 'تعديل',
  'continue': 'استمرار',
  'logOut': 'تسجيل الخروج',
  'OK': 'حسناً',
  'user': 'User',
  'name': 'الاسم',
  'chooseOption': 'اختر طريقة التقاط الصورة',
  'camera': 'الكاميرا',
  'gallery': 'المعرض',
};
