Map<String, String> coreEn = {
  'appName': 'Deliverzler',
  'fontFamily': 'poppins',
  'dateFormat': 'en',
  'noInternetConnection': 'No internet connection',
  'pleaseCheckYourDeviceNetwork':
      'Please check your device\'s network connection.',
  'retry': 'Retry',
  'oops': 'Oops!',
  'somethingWentWrong': 'Something went wrong.',
  'pleaseTryAgainLater': 'Please try again later!',
  "ThisFieldIsEmpty": "This field is empty",
  "pleaseEnterValidNumber": "Please enter a valid mobile number",
  "pleaseEnterValidEmail": "Please enter a valid email address",
  "pleaseEnterValidName": "Please enter a valid name",
  "nameMustBeAtLeast2Letters": "Name must be at least 2 Letters",
  "nameMustBeAtMost30Letters": "Name must be at most 30 Letters",
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'back': 'Back',
  'edit': 'Edit',
  'continue': 'Continue',
  'logOut': 'Log out',
  'OK': 'OK',
  'user': 'User',
  'name': 'Name',
  'chooseOption': 'Choose Option',
  'camera': 'Camera',
  'gallery': 'Gallery',
};
